feat: community page
electron/electronjs.org-new pull request #133
Opened 2021-10-27 02:11 UTC by validity-check

As promised in #76, I've made a community page. It features: a "subtron" at the top which is dark and light mode friendly; a section on the different communities one can become invlovled in; and some language communities that one can join. This should be a good starting point for a community section, and I would like to be let know of any amendments that can be made to make it a better one.

This is my first PR on this repository, and it probably won't be the last 😃.

Thank you for reading.

2021-10-29 18:18 UTC, molant commented
@erickzhao I'm thinking about doing some clean-up on this page while we are at it. If we agree on those I can take care of the changes @validity-check or you can do it if you have time 😊

I think we can remove a bunch of links that apply mostly to GitHub.

- Get started building an app by reading the quick-start guide
- Get help and feedback by joining the Discord server, or visiting Stack Overflow
- Donate on our OpenCollective page.
- Participate in the project in the electron GitHub organization
- Report Code of Conduct violations by emailing coc@electronjs.org
- Report security issues by emailing security@electronjs.org

The videos section might be worth moving to a documentation page. There's been a few people asking about those and I don't think they are easy to discover buried in this page.
The same goes for Tools, components and boilerplates. Or we move some to the documentation or we remove them entirely.

Thoughts about all of this?

2021-10-29 18:55 UTC, erickzhao requested changes

2021-10-29 18:55 UTC, erickzhao commented on src/pages/community.js
> +import styles from './index.module.scss';
I'd create a separate `community.module.scss` file here

2021-10-29 18:55 UTC, erickzhao commented on src/pages/community.js
> +      <div className={clsx('community_section', styles.community_section)}>
Since we're using a CSS module, you don't need to actually add `community_section` as a class here

2021-10-29 18:55 UTC, erickzhao commented on src/pages/community.js
> +      <div className={clsx('subtron', styles.subtron)}>
If this subtron is meant to be reusable, we could potentially move it to its own component.

2021-10-29 18:55 UTC, erickzhao commented on src/pages/index.module.scss
> +  padding-right: 12px !important;
Would prefer to not use `!important` if possible.

2021-10-29 18:55 UTC, erickzhao commented on src/pages/index.module.scss
> +  }
We should add reusable color codes to the global `custom.scss` styles.

2021-10-29 18:55 UTC, erickzhao commented on src/pages/index.module.scss
> +.community_section {
With CSS modules, prefer to use `.camelCase` styles

2021-11-02 22:21 UTC, validity-check commented
I'm sorry, I've been very busy for the past few days. I'll be able to get to this tomorrow hopefully.

2021-11-05 19:38 UTC, validity-check commented
I thought I'd get more free time, but I haven't (I've only gotten more busy), and I think it would be better if I let it to you guys. In any case, thank you for your patience and I hope I've helped you.

2021-11-05 20:46 UTC, erickzhao commented
No problem @validity-check !

2022-03-24 23:43 UTC, closed without merging