docs: modify sidebar
electron/electronjs.org-new pull request #256
Opened 2022-08-26 22:31 UTC by georgexu99

This change is part of a larger set of changes with the purpose of providing new electron forge users with a better experience navigating the documentation to find standard forge configuration tasks such as:
* setting app icons
* code signing
* packaging, making and publishing their apps

this pr is blocked by: https://github.com/electron/electron/pull/35473

related:
https://github.com/electron-forge/electron-forge-docs/pull/71
https://github.com/electron-userland/electron-forge/issues/1836#issuecomment-660580058

2022-08-31 22:05 UTC, VerteDinde approved these changes
Content looks good, merge contingent on the e/e PR merging first 👍

2022-09-06 23:57 UTC, erickzhao requested changes
Requesting changes since the docs pr has not landed so this should not be merged yet

2022-09-19 22:19 UTC, erickzhao requested changes

2022-09-19 22:19 UTC, erickzhao commented on sidebars.js
> +          label: 'Advanced Distribution Guides',
```suggestion
          label: 'Advanced Reference',
```

2022-10-03 20:44 UTC, erickzhao approved these changes

2022-10-03 20:45 UTC, merged